services:
  mainsail:
    container_name: mainsail
    build:
      context: ./mainsail
      dockerfile: Dockerfile
    networks:
      moonraker-network:
    ports:
      - 8080:80
    volumes:
      - ./mainsail/config.json:/usr/share/nginx/html/config.json
    depends_on:
      - moonraker

  moonraker:
    container_name: moonraker
    build:
      context: .
      dockerfile: moonraker/Dockerfile
    networks:
      moonraker-network:
    expose:
      - 7125
    volumes:
      - klipper_logs:/home/klipper_logs
    depends_on:
      - klipper
  
  klipper:
    container_name: klipper
    build:
      context: .
      dockerfile: klipper/Dockerfile
    volumes:
      - klipper_logs:/home/klipper_logs

networks:
  moonraker-network:

volumes:
  klipper_logs:
